### ISSUE TITLE
Rewrite split layouts

### ISSUE THREAD

**Issue by rock3r** [JetBrains/jewel#273]
In some cases the `SplitLayout`s don't work correctly when dragging the divider. They also have other issues (see #263 and #277). We should rewrite them, fixing the bugs and allowing nesting. We can look at the core logic of Accompanist's [`TwoPane`](https://github.com/google/accompanist/blob/main/adaptive/src/main/java/com/google/accompanist/adaptive/TwoPane.kt) component for inspiration.

## Basic requirements
* Nesting
* Min/Max sizing in `dp`
* Divider must be draggable to resize with a mouse
* Draggable area is `1.dp` wider than the border
* Divider must not be focusable

## Tasks

- [x] Add draggable divider
- [x] Style the divider 
- [x] Prevent divider from being focused
- [x] Allow nesting
- [x] Allow resizing with minimum width parameter
- [ ]

**Comment by rock3r** [comment]
I'm considering rewriting the split layouts based on the core logic of Accompanist's [`TwoPane`](https://github.com/google/accompanist/blob/main/adaptive/src/main/java/com/google/accompanist/adaptive/TwoPane.kt) component
